### ISSUE TITLE
apply custom values from local file

### ISSUE THREAD

**Issue by kpoxo6op** [kpoxo6op/soyspray#4]
understand how to get away from providing path to value URL

```yaml
spec:
  project: default
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 65.5.0
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - https://raw.githubusercontent.com/kpoxo6op/soyspray/work/playbooks/yaml/argocd-apps/prometheus/values.yaml
```

ArgoCD apps must support better way
