### ISSUE TITLE
Longhorn RWX volumes fail with I/O error code 5 (EIO) while RWO works perfectly

### ISSUE THREAD

**Issue by kpoxo6op** [kpoxo6op/soyspray#51]
# Longhorn RWX Volume I/O Error Investigation - Expert Analysis Needed

## **Problem Summary**

Longhorn RWX (ReadWriteMany) volumes consistently fail with I/O error code 5
(EIO) while RWO (ReadWriteOnce) volumes on the same storage work perfectly. This
issue persists across different storage hardware (USB and Samsung SSD) and fresh
cluster deployments.

### **Cluster Configuration**

- **Kubernetes**: Fresh cluster with Kubespray v2.27
- **Longhorn**: v1.8.0 deployed via ArgoCD
- **Nodes**: Single-node cluster (node-0: 192.168.1.103)
- **OS**: Ubuntu 24.10 (6.11.0-26-generic)
- **Storage**: Samsung SSD 870 (465GB) mounted at `/storage` with ext4

### **Storage Migration History**

- **Previous**: USB drive (113GB) with same I/O errors
- **Current**: Samsung SSD (465GB) - same I/O errors persist
- **Filesystem**: ext4 on both devices
- **Mount**: `/dev/sda1 /storage ext4 defaults 0 2`

### **Key Settings**

```yaml
default-data-path: /storage
default-replica-count: 1
rwx-volume-fast-failover: false
```

### **Storage Classes**

```yaml
# RWO StorageClass (WORKING)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate

# RWX StorageClass (FAILING)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx
provisioner: driver.longhorn.io
parameters:
  share: "true"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

### Longhorn values

```yaml
persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
  defaultDataLocality: best-effort
  migratable: true
  metricsPort: 9500

defaultSettings:
  defaultDataLocality: best-effort
  defaultReplicaCount: 1
  defaultDataPath: "/storage"
  deletingConfirmationFlag: true
  orphanAutoDeletion: true
  backupstorePollInterval: 300
  concurrentReplicaRebuildPerNodeLimit: 1
  snapshotMaxCount: 10
  autoCleanupSystemGeneratedSnapshot: true
  autoCleanupRecurringJobBackupSnapshot: true
  replicaAutoBalance: "disabled"
  fastReplicaRebuildEnabled: "true"
  snapshotDataIntegrity: disabled

longhornUI:
  replicas: 1

longhornManager:
  priorityClass: longhorn-critical
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 5

longhornDriver:
  priorityClass: longhorn-critical

engineImage:
  livenessProbe:
    initialDelaySeconds: 45
    periodSeconds: 15
  readinessProbe:
    initialDelaySeconds: 45
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: false

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

priorityClass:
  create: true
  name: longhorn-critical
  value: 2000001001

ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.soyspray.vip
  tls: true
  tlsSecret: prod-cert-tls
  path: /
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx

service:
  ui:
    type: ClusterIP
  manager:
    type: ClusterIP
    nodePort: ""
    ports:
      manager: 9500
      metrics: 9500

metrics:
  serviceMonitor:
  # manual flip required from false to true when prometheus is ready
    enabled: false
    additionalLabels:
      release: kube-prometheus-stack
    port: manager
    interval: 60s
    scrapeTimeout: 30s
```

### **Kubespray Addons Configuration**

```yaml
# From kubespray/inventory/soycluster/group_vars/k8s_cluster/addons.yml
local_volume_provisioner_enabled: true
local_volume_provisioner_storage_classes:
  local-storage:
    host_dir: /mnt/disks
    mount_dir: /mnt/disks
    volume_mode: Filesystem
    fs_type: ext4

metallb_enabled: true
metallb_config:
  address_pools:
    primary:
      ip_range:
        - 192.168.1.120-192.168.1.140

argocd_enabled: true
argocd_version: v2.12.4
```

### **✅ RWO Volume Test - SUCCESS**

```bash
# Created test PVC with longhorn storageclass
kubectl create -f - << EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rwo
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
EOF

# Test pod with RWO volume
kubectl exec -n media test-pod -- ls -la /test
total 24
drwxr-xr-x    3 root     root          4096 Jun 22 08:48 .
drwxr-xr-x    1 root     root          4096 Jun 22 08:48 ..
drwx------    2 root     root         16384 Jun 22 08:48 lost+found

kubectl exec -n media test-pod -- touch /test/working.txt
# SUCCESS: RWO volume works perfectly
```

### **❌ RWX Volume Test - FAILURE**

```bash
# qbittorrent pod with RWX volume
kubectl exec -n media qbittorrent-74977cc679-knb8s -- ls -la /downloads
ls: reading directory '/downloads': I/O error
total 0
command terminated with exit code 2
```

### **NFS Share Manager Logs**

```
# NFS server starts successfully
time="2025-06-22T08:36:48Z" level=info msg="Starting nfs server, volume is ready for export"
time="2025-06-22T08:36:48Z" level=info msg="Running NFS server!"

# But I/O errors occur during operations
Error I/O error with error code 5 in nfs4_write_cb converted to NFS4ERR_IO
posix2fsal_error :FSAL :INFO :Mapping 5 to ERR_FSAL_IO
```

### **Volume Mount Information**

```bash
# RWX volume mounted as NFS but failing
kubectl exec -n media qbittorrent-pod -- mount | grep downloads
10.42.0.7:/export/pvc-4ce4bf72-b979-4a5e-9767-2353983ce726 on /downloads type nfs4

# Share manager pod running
kubectl get pods -n longhorn-system | grep share-manager
share-manager-pvc-4ce4bf72-b979-4a5e-9767-2353983ce726   1/1     Running   0   10m
```

## **Current PVC Status**

```bash
kubectl get pvc -n media
NAME                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
qbittorrent-downloads   Bound    pvc-4ce4bf72-b979-4a5e-9767-2353983ce726   500Mi      RWX            longhorn-rwx   25m
```

## **Business Requirement**

**RWX volumes are CRITICAL** for the media stack architecture:

- **qBittorrent**: Downloads files to `/downloads` (RWX volume)
- **Readarr**: Reads from same `/downloads` volume for post-processing
- **Calibre-Web**: Reads processed files from same volume
- **Multiple pods need simultaneous read access** to downloaded content

## **Key Question for Expert Analysis**

**Why do Longhorn RWX volumes consistently fail with I/O error code 5 (EIO)
while RWO volumes on the same Samsung SSD storage work perfectly?**

### **Specific Technical Questions:**

1. **Single-Replica Issue**: Is `default-replica-count: 1` causing RWX stability
   issues? Does Longhorn RWX require multiple replicas for proper NFS operation?

2. **NFS Configuration**: Are there known Longhorn NFS/RWX configuration issues
   with single-node clusters or specific settings that need adjustment?

3. **Fast Failover**: Would enabling `rwx-volume-fast-failover: true` resolve
   the NFS stability issues?

4. **Storage Path**: Could the `/storage` mount point or ext4 filesystem
   configuration be incompatible with Longhorn's NFS share manager?

5. **Alternative Solutions**: Are there recommended workarounds for RWX
   functionality in single-node Longhorn deployments, or alternative storage
   solutions that provide reliable RWX capabilities?

### **What Works vs What Fails**

- ✅ **RWO volumes**: Perfect I/O performance, no errors
- ✅ **Samsung SSD**: Hardware verified working with RWO
- ✅ **NFS server startup**: Share manager starts without errors
- ❌ **RWX I/O operations**: Consistent EIO errors on file operations
- ❌ **Cross-hardware persistence**: Same issue on USB and SSD

### **Troubleshooting Steps Already Attempted**

1. Storage hardware migration (USB → Samsung SSD)
2. Fresh cluster deployment
3. PVC/Pod deletion and recreation
4. Share manager log analysis
5. Direct RWO vs RWX comparison testing

**Need expert guidance on Longhorn RWX configuration, known issues, and
recommended solutions for reliable multi-pod file sharing in single-node
clusters.**
